// src/components/ModuleEditor/CellGroup.tsx
import Cell from "./Cell";
import { useCallback, useEffect, useState } from "react";

type CellGroupProps = {
  maxLength: number;
  radix: number;
  value: number;
  defaultCellStr: string;
  allowZero?: boolean;
  yPositionInGrid: number;
  xPositionInGrid: number;
};

function CellGroup({
  maxLength,
  radix,
  value,
  defaultCellStr,
  allowZero,
  yPositionInGrid,
  xPositionInGrid,
}: CellGroupProps) {
  const createValueWithDefaultPrefix = useCallback(() => {
    const num = value === 0 ? "" : value.toString(radix).toUpperCase();
    return num.padStart(maxLength, defaultCellStr);
  }, [value, radix, maxLength, defaultCellStr]);

  const [valueWithDefaultPrefix, setValueWithDefaultPrefix] = useState(
    createValueWithDefaultPrefix
  );

  useEffect(() => {
    setValueWithDefaultPrefix(createValueWithDefaultPrefix());
  }, [value, createValueWithDefaultPrefix]);

  return (
    <>
      {valueWithDefaultPrefix.split("").map((char, i) => (
        <Cell
          yPositionInGrid={yPositionInGrid}
          xPositionInGrid={i + xPositionInGrid}
          defaultDisplayValue={defaultCellStr}
          key={i}
          str={char}
          allowZero={allowZero}
        />
      ))}
    </>
  );
}

export default CellGroup;

// src/lib/components/ModuleEditor/CellGroup.svelte
<script lang="ts">
	import Cell from './Cell.svelte';

	export let maxLength: number;
	export let radix: number;
	export let value = 0;
	export let defaultCellStr: string;
	export let allowZero = false;
	export let yPositionInGrid: number;
	export let xPositionInGrid: number;

	$: valueWithDefaultPrefix = createValueWithDefaultPrefix();

	function createValueWithDefaultPrefix(): string {
		const num = value === 0 ? '' : value.toString(radix).toUpperCase();
		return num.padStart(maxLength, defaultCellStr);
	}
</script>

{#each valueWithDefaultPrefix.split('') as char, i}
	<Cell
		{yPositionInGrid}
		xPositionInGrid={i + xPositionInGrid}
		defaultDisplayValue={defaultCellStr}
		str={char}
		{allowZero}
	/>
{/each}
