// src/components/ModuleEditor/ModuleEditor.jsx
import { useEffect, useState } from "react";

function ModuleEditor({ currentModule }) {
  const [module, setModule] = useState({ ...currentModule });
  const [currentPattern, setCurrentPattern] = useState(
    currentModule.patterns[0]
  );
  const [currentPatternIndex, setCurrentPatternIndex] = useState(0);

  useEffect(() => {
    setModule({ ...currentModule });
    changePattern(0);
  }, [currentModule]);

  function changePattern(index) {
    setCurrentPattern(currentModule.patterns[index]);
    setCurrentPatternIndex(index);
  }

  function changeModuleProp(field) {
    return (e) => {
      setModule({ ...module, [field]: e.target.value });
    };
  }

  return (
    <div className="px-4 bg-slate-600 self-center w-full rounded-xl shadow-slate-900 drop-shadow-md max-w-[1080px]">
      <div className="flex py-6 gap-4 text-slate-900 font-mono text-sm">
        <div className="grow">
          <span className="text-slate-400">Title:</span>
          <input
            type="text"
            className="px-2 mt-2 block w-full bg-white rounded-md text-sm shadow-sm"
            value={module.title}
            onChange={changeModuleProp("title")}
          />
        </div>
        <div className="grow">
          <span className="text-slate-400">Author:</span>
          <input
            type="text"
            className="px-2 mt-2 block w-full bg-white rounded-md text-sm shadow-sm"
            value={module.author}
            onChange={(e) => {
              setModule({ ...module, author: e.target.value });
            }}
          />
        </div>
      </div>
      <div className="flex overflow-auto text-center text-xl shadow-slate-900 font-mono gap-[2px]">
        {module.patterns.map((p, i) =>
          currentPatternIndex === i ? (
            <div
              key={i}
              className="flex-shrink-0 w-8 rounded-sm bg-blue-600 cursor-default text-slate-200 border border-blue-400"
            >
              {p.number}
            </div>
          ) : (
            <div
              key={i}
              onClick={() => changePattern(i)}
              class="flex-shrink-0 w-8 hover:bg-slate-400 rounded-sm cursor-pointer bg-slate-500 text-slate-900 border border-slate-400"
            >
              {p.number}
            </div>
          )
        )}
      </div>
    </div>
  );
}

export default ModuleEditor;

// src/lib/components/ModuleEditor/ModuleEditor.svelte
<script lang="ts">
	import {
		currentPatternIndex,
		cursorPosition,
		moduleAuthor,
		moduleTitle,
		patterns
	} from '$lib/stores/stores.js';
	import PatternEditor from './PatternEditor.svelte';

	function switchPattern(index: number) {
		currentPatternIndex.set(index);
		cursorPosition.setPosition(0, 0);
	}
</script>

<div
	class="w-full min-h-0 self-center rounded-xl bg-slate-600 px-4 shadow-slate-900 drop-shadow-md max-w-[1080px] flex flex-col"
>
	<div class="flex gap-4 py-2 font-mono text-xs text-slate-900">
		<div class="grow">
			<span class="text-slate-400">Title:</span>
			<input
				type="text"
				class="mt-1 block w-full rounded-md bg-white px-2 text-sm shadow-sm"
				bind:value={$moduleTitle}
			/>
		</div>
		<div class="grow">
			<span class="text-slate-400">Author:</span>
			<input
				type="text"
				class="mt-1 block w-full rounded-md bg-white px-2 text-sm shadow-sm"
				bind:value={$moduleAuthor}
			/>
		</div>
	</div>
	<div
		class="flex flex-shrink-0 overflow-auto text-center font-mono text-md shadow-slate-900 gap-[2px] select-none"
	>
		{#each $patterns as pattern, i (i)}
			<button
				class="w-7 flex-shrink-0 {i === $currentPatternIndex
					? 'cursor-default rounded-sm border border-blue-400 bg-blue-600 text-slate-200'
					: 'cursor-pointer rounded-sm border border-slate-400 bg-slate-500 text-slate-900 hover:bg-slate-400'}"
				on:click={() => switchPattern(i)}
			>
				{pattern.number}
			</button>
		{/each}
	</div>
	<PatternEditor />
</div>
