// src/lib/components/ModuleEditor/Cell.svelte
<script lang="ts">
	import { cursorPosition } from '$lib/stores/stores';

	export let str: string;
	export let defaultDisplayValue: string | undefined = undefined;
	export let allowZero = false;
	export let xPositionInGrid: number | undefined = undefined;
	export let yPositionInGrid: number;

	function cursorToCellPosition() {
		if (xPositionInGrid === undefined) return;
		cursorPosition.setPosition(xPositionInGrid, yPositionInGrid);
	}

	$: isValueOrDefault =
		(defaultDisplayValue && str === '0' && !allowZero) || str == defaultDisplayValue;

	$: isPositionMatched =
		xPositionInGrid === $cursorPosition.posX && yPositionInGrid === $cursorPosition.posY;

	$: displayValue = isValueOrDefault ? defaultDisplayValue : str;
</script>

<span
	on:click={cursorToCellPosition}
	class:text-slate-500={isValueOrDefault}
	class:bg-blue-50={isPositionMatched}
	class:text-black={isPositionMatched}
	class:animate-[pulse_1.2s_linear_infinite]={isPositionMatched}
>
	{displayValue}
</span>

// src/components/ModuleEditor/Cell.tsx
import classNames from "classnames";
import { useBoundStore } from "../../stores";

type CellProps = {
  str: string;
  defaultDisplayValue?: string;
  allowZero?: boolean;
  xPositionInGrid?: number;
  yPositionInGrid: number;
};

function Cell({
  str,
  defaultDisplayValue,
  allowZero,
  xPositionInGrid,
  yPositionInGrid,
}: CellProps) {
  const { posX, posY, setPosition } = useBoundStore((state) => ({
    posX: state.posX,
    posY: state.posY,
    setPosition: state.setPosition,
  }));

  function cursorToCellPosition() {
    if(xPositionInGrid === undefined) return;

    return setPosition(xPositionInGrid, yPositionInGrid);
  }

  const isValueOrDefault =
    (defaultDisplayValue && str === "0" && !allowZero) ||
    str === defaultDisplayValue;

  const displayValue = isValueOrDefault ? defaultDisplayValue : str;

  const classes = classNames({
    "text-slate-500": isValueOrDefault,
    "bg-blue-200 text-black animate-[pulse_1.2s_linear_infinite]":
      xPositionInGrid !== undefined &&
      xPositionInGrid === posX &&
      yPositionInGrid === posY,
    "": true,
  });

  return (
    <span onClick={cursorToCellPosition} className={classes}>
      {displayValue}
    </span>
  );
}

export default Cell;
