// src/lib/components/PatternEditor/EditorRow.svelte
<script lang="ts">
	import type PatternRow from '$lib/models/pattern-row.js';
	import { Note } from '$lib/models/note-data';
	import CellGroup from '../CellGroup.svelte';

	export let row: PatternRow;
	export let index = 0;
	export let globalIndex = 0;

	$: hexIndex = index.toString(16).padStart(2, '0').toUpperCase();
	$: classesBase = `${$$props.class ?? ''}`;

	function isCharVisible(char: string) {
		return char !== '.';
	}
</script>

<div class="flex relative {classesBase}">
	<CellGroup
		coordinates={{ startingXPosition: -1, yPosition: globalIndex }}
		class="px-2"
		condition={(_hexValue) => index % 4 === 0}
		trueClass="text-blue-200"
		falseClass="text-blue-300"
		values={hexIndex}
	/>
	<div class="px-2 flex border-l border-slate-600">
		<CellGroup
			condition={(envChar) => isCharVisible(envChar)}
			trueClass="text-cyan-400"
			coordinates={{ startingXPosition: 0, yPosition: globalIndex }}
			values={row.envelopeValue.split('')}
		/>
	</div>
	<div class="px-2 flex gap-[0.5px] border-l border-slate-600">
		<CellGroup
			condition={(noiseChar) => isCharVisible(noiseChar)}
			trueClass="text-cyan-400"
			values={row.noiseValue.split('')}
			coordinates={{ startingXPosition: 4, yPosition: globalIndex }}
		/>
	</div>

	{#each row.channels as channel, index (channel)}
		{#each channel.channelRows as channelRow (row)}
			<div class="px-2 flex border-l border-slate-600">
				<div class="px-1 flex gap-[0.5px]">
					<CellGroup
						values={channelRow.noteData}
						coordinates={{ startingXPosition: 6 + index * 9, yPosition: globalIndex }}
						condition={(noteData) => noteData.note !== Note.None}
						trueClass="text-blue-100"
					/>
				</div>
				<div class="px-1 flex gap-[0.5px]">
					<CellGroup
						values={[
							channelRow.instrument,
							channelRow.envelope,
							channelRow.ornament,
							channelRow.volume
						]}
						coordinates={{ startingXPosition: 7 + index * 9, yPosition: globalIndex }}
						condition={(value) => value !== '.'}
						trueClass="text-blue-300"
					/>
				</div>
				<div class="px-1 flex gap-[0.5px]">
					<CellGroup
						values={[
							channelRow.effect,
							channelRow.effectParamX,
							channelRow.effectParamY,
							channelRow.effectParamZ
						]}
						coordinates={{
							startingXPosition: 11 + index * 9,
							yPosition: globalIndex
						}}
						condition={(value) => value !== '.'}
						trueClass="text-yellow-200"
					/>
				</div>
			</div>
		{/each}
	{/each}
</div>

// src/components/ModuleEditor/EditorRow.tsx
import Cell from "./Cell";
import CellGroup from "./CellGroup";
import ChannelRow from "./ChannelRow";
import PatternRow from "../../models/pattern-row";
import Channel from "../../models/channel";

type EditorRowProps = {
  row: PatternRow;
  index: number;
  channels: Channel[];
  bgEndOfBar?: string;
};

function EditorRow({ row, index, channels, bgEndOfBar }: EditorRowProps) {
  function applyStyleWhenEndOfBar(normalStyle?: string, endStyle?: string) {
    if (index % 4 === 0) {
      return endStyle + " " + bgEndOfBar;
    } else {
      return normalStyle;
    }
  }

  return (
    <div className="flex relative" style={{ top: `${0}px` }}>
      <Cell
        className={
          applyStyleWhenEndOfBar("text-blue-300", "text-blue-200") + " px-2"
        }
        str={index.toString(16).padStart(2, "0").toUpperCase()}
      />
      <span className="border border-slate-900" />
      <CellGroup
        className={applyStyleWhenEndOfBar() + " px-2"}
        maxLength={4}
        radix={16}
        value={row.envelopeValue}
        defaultCellStr="."
        allowZero={true}
      />
      <span className="border border-slate-900" />
      <CellGroup
        className={applyStyleWhenEndOfBar() + " px-2"}
        maxLength={2}
        radix={16}
        value={row.noiseValue}
        defaultCellStr="."
        allowZero={true}
      />
      <span className="border border-slate-900" />
      <ChannelRow
        className={applyStyleWhenEndOfBar()}
        row={channels[0].channelRows[index]}
      />
      <span className="border border-slate-900" />
      <ChannelRow
        className={applyStyleWhenEndOfBar()}
        row={channels[1].channelRows[index]}
      />
      <span className="border border-slate-900" />
      <ChannelRow
        className={applyStyleWhenEndOfBar()}
        row={channels[2].channelRows[index]}
      />
    </div>
  );
}

export default EditorRow;
