// src/lib/components/ModuleEditor/RowContainer.svelte
<script lang="ts">
	import { cursorPosition } from '$lib/stores/stores.js';

	export let yPositionInGrid: number;
	export let className = '';

	$: isMultipleOfFour = yPositionInGrid % 4 === 0;
	$: isNotMultipleOfFour = yPositionInGrid % 4 !== 0;
	$: isActivePosition = $cursorPosition.posY === yPositionInGrid;
</script>

<span
	class="{className} px-2"
	class:text-blue-300={isNotMultipleOfFour}
	class:text-blue-200={isMultipleOfFour}
	class:bg-blue-800={isActivePosition}
	class:bg-slate-700={isMultipleOfFour && !isActivePosition}
>
	<slot />
</span>

// src/components/ModuleEditor/RowContainer.tsx
import classNames from "classnames";
import { useBoundStore } from "../../stores";
import React from "react";

type RowContainerProps = {
  yPositionInGrid: number;
  className?: string;
  children: React.ReactNode;
};

function RowContainer({
  yPositionInGrid,
  children,
  className,
}: RowContainerProps) {
  const { posY } = useBoundStore((state) => ({ posY: state.posY }));

  const classes = classNames(
    {
      "text-blue-300": yPositionInGrid! % 4,
      "text-blue-200": yPositionInGrid % 4 === 0,
      "bg-blue-800": posY === yPositionInGrid,
      "bg-slate-700": yPositionInGrid % 4 === 0 && posY !== yPositionInGrid,
    },
    className,
    "px-2"
  );

  return <span className={classes}>{children}</span>;
}

export default RowContainer;
